### ISSUE TITLE
A bug with the background 

### ISSUE THREAD

**Issue by Hussainamin10** [Vapidx4/Dryad-s-Proto#2]
At first, when you start to play the game maybe it will be cleaner and easier if you put the control instructions in a button called instruction so that it will be easier to access it. Also when you want to play the game in full screen there is a issue with the size it gets suddenly bigger than the screen and it moves to the left bottom.

Hussain Amin

**Comment by Vapidx4** [comment]
Bug is most likely caused by the size of your screen, as the world dimensions are set differently
